email = 'maxim.cudaew@gmail.com'
password = 'Qwerty123'

local_demoqa_url = "localhost:5555"
test_demoqa_url = "http://your_test_demoqa_env.com"
test2_demoqa_url = "http://your_test2_demoqa_env.com"
demo_web_prod_url = 'https://demowebshop.tricentis.com'
local_regress_in_url = "localhost:5555"
test_regress_in_url = "http://your_test_demoqa_env.com"
test2_regress_in_url = "http://your_test2_demoqa_env.com"
prod_regress_in_url = 'https://reqres.in'